
[font]
size = 12.0

[font.normal]
#family = "FiraCodeNerdFontMono"
family = "LiberationMono"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.45
startup_mode = "Maximized"

[window.padding]
x = 18
y = 16

[general]
live_config_reload = true

# theme
import = [ "~/.config/alacritty/themes/themes/gruvbox_dark.toml" ]
